### ISSUE TITLE
Flacon doesn't recognize the length of the last track

### ISSUE THREAD

**Issue by MPalinux** [flacon/flacon#116] opened 2020-04-19 11:17 UTC
Hi all, 
I always use Flacon with good  results, however, when i try to open some files, a little red square with a little white cross appears on the image of the Album and Flacon seems not to be able to determine the length of the last track; instead of the time, two question marks are shown.
The original file works fine when I play it as a single track, so I can rule out corruptions of the file.

Is it a known bug?
Tks a lot

**Comment by SokoloffA** [comment] 2020-06-06 18:02
I'm sorry for the long silence.
Please check in the new version of the Flacon. If the problem persists, send me the problem CUE file. And also I need information about the file duration, send me the output of the following command:
```
ffprobe -show_streams YOUR_INPUT_AUDIO_FILE
```
or 

```
 mediainfo -f YOUR_INPUT_AUDIO_FILE
```

**Comment by msdobrescu** [comment] 2020-08-17 18:27
Hi, in my experience, I get this error when "\" character is present in the title of the song.

**Comment by SokoloffA** [comment] 2020-09-05 12:20
Sorry for the long silence, I was offline these days.
Please send me your CUE file.

**Comment by FrancisCote1234** [comment] 2021-02-18 13:37
I have the same problem.

Here the mediainfo info

`General
Count                                    : 328
Count of stream of this kind             : 1
Kind of stream                           : General
Kind of stream                           : General
Stream identifier                        : 0
Count of audio streams                   : 1
Audio_Format_List                        : FLAC
Audio_Format_WithHint_List               : FLAC
Audio codecs                             : FLAC
Complete name                            : A Time To Remember - 1990 - Happy Birthday.flac
File name                                : A Time To Remember - 1990 - Happy Birthday
File extension                           : flac
Format                                   : FLAC
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Format/Url                               : https://xiph.org/flac/
Format/Extensions usually used           : flac
Commercial name                          : FLAC
Codec                                    : FLAC
Codec                                    : FLAC
Codec/Info                               : Free Lossless Audio Codec
Codec/Url                                : https://xiph.org/flac/
Codec/Extensions usually used            : flac
File size                                : 552360890
File size                                : 527 MiB
File size                                : 527 MiB
File size                                : 527 MiB
File size                                : 527 MiB
File size                                : 526.8 MiB
Duration                                 : 4643893
Duration                                 : 1 h 17 min
Duration                                 : 1 h 17 min 23 s 893 ms
Duration                                 : 1 h 17 min
Duration                                 : 01:17:23.893
Duration                                 : 01:17:23.893
Overall bit rate mode                    : VBR
Overall bit rate mode                    : Variable
Overall bit rate                         : 951548
Overall bit rate                         : 952 kb/s
Stream size                              : 0
Stream size                              : 0.00 Byte (0%)
Stream size                              :  Byte0
Stream size                              : 0.0 Byte
Stream size                              : 0.00 Byte
Stream size                              : 0.000 Byte
Stream size                              : 0.00 Byte (0%)
Proportion of this stream                : 0.00000
Title                                    : Right Here, Right Now
Album                                    : A Time To Remember - 1990 - Happy Birthday
Track name                               : Right Here, Right Now
Track name/Position                      : 2
Performer                                : Jesus Jones
Genre                                    : Pop
Recorded date                            : 1999
File last modification date              : UTC 2021-02-18 01:33:10
File last modification date (local)      : 2021-02-17 20:33:10
Comment                                  : EAC 0.95beta4 / FLAC 1.1.2 q6

Audio
Count                                    : 275
Count of stream of this kind             : 1
Kind of stream                           : Audio
Kind of stream                           : Audio
Stream identifier                        : 0
Format                                   : FLAC
Format/Info                              : Free Lossless Audio Codec
Format/Url                               : https://xiph.org/flac/
Commercial name                          : FLAC
Codec                                    : FLAC
Codec                                    : FLAC
Duration                                 : 4643893
Duration                                 : 1 h 17 min
Duration                                 : 1 h 17 min 23 s 893 ms
Duration                                 : 1 h 17 min
Duration                                 : 01:17:23.893
Duration                                 : 01:17:23.893
Bit rate mode                            : VBR
Bit rate mode                            : Variable
Bit rate                                 : 951526
Bit rate                                 : 952 kb/s
Channel(s)                               : 2
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Channel positions                        : 2/0/0
Sampling rate                            : 44100
Sampling rate                            : 44.1 kHz
Samples count                            : 204795680
Resolution                               : 16
Resolution                               : 16 bits
Bit depth                                : 16
Bit depth                                : 16 bits
Stream size                              : 552348159
Stream size                              : 527 MiB (100%)
Stream size                              : 527 MiB
Stream size                              : 527 MiB
Stream size                              : 527 MiB
Stream size                              : 526.8 MiB
Stream size                              : 527 MiB (100%)
Proportion of this stream                : 0.99998
Writing library                          : reference libFLAC 1.1.0 20030126
Writing library                          : libFLAC 1.1.0 (UTC 2003-01-26)
Encoded_Library_Name                     : libFLAC
Encoded_Library_Version                  : 1.1.0
Encoded_Library_Date                     : UTC 2003-01-26
`

Here's the cue files:

`PERFORMER "Various"
TITLE "A Time To Remember - 1990 - Happy Birthday"
FILE "A Time To Remember - 1990 - Happy Birthday.flac" WAVE
  TRACK 01 AUDIO
    TITLE "Unbelieveable"
    PERFORMER "E.M.F."
    INDEX 01 00:00:00
  TRACK 02 AUDIO
    TITLE "Right Here, Right Now"
    PERFORMER "Jesus Jones"
    INDEX 00 03:30:60
    INDEX 01 03:31:00
  TRACK 03 AUDIO
    TITLE "There Anybody Out There"
    PERFORMER "Bassheads"
    INDEX 01 06:40:42
  TRACK 04 AUDIO
    TITLE "Thinking About Your Love"
    PERFORMER "Keny Thomas"
    INDEX 00 10:08:42
    INDEX 01 10:09:20
  TRACK 05 AUDIO
    TITLE "Sleeping Satellite"
    PERFORMER "Tasmin Archer"
    INDEX 00 14:05:27
    INDEX 01 14:06:00
  TRACK 06 AUDIO
    TITLE "Goodbye"
    PERFORMER "Sundays"
    INDEX 00 18:42:50
    INDEX 01 18:43:70
  TRACK 07 AUDIO
    TITLE "Down That Road"
    PERFORMER "Shara Nelson"
    INDEX 00 23:27:20
    INDEX 01 23:27:67
  TRACK 08 AUDIO
    TITLE "Let Me Show You"
    PERFORMER "K. Klass"
    INDEX 00 27:12:50
    INDEX 01 27:13:05
  TRACK 09 AUDIO
    TITLE "I Like To Move It"
    PERFORMER "Real 2 Real"
    INDEX 00 30:45:22
    INDEX 01 30:46:05
  TRACK 10 AUDIO
    TITLE "Trouble"
    PERFORMER "Shampoo"
    INDEX 00 34:37:07
    INDEX 01 34:37:67
  TRACK 11 AUDIO
    TITLE "Respect"
    PERFORMER "Judy Cheeks"
    INDEX 00 37:52:50
    INDEX 01 37:53:07
  TRACK 12 AUDIO
    TITLE "The Bomb"
    PERFORMER "Bucketheads"
    INDEX 01 41:13:47
  TRACK 13 AUDIO
    TITLE "Spaceman"
    PERFORMER "Babylon Zoo"
    INDEX 00 44:36:55
    INDEX 01 44:37:25
  TRACK 14 AUDIO
    TITLE "Not So Manic Now"
    PERFORMER "Dubstar"
    INDEX 01 48:42:12
  TRACK 15 AUDIO
    TITLE "Delicious"
    PERFORMER "Catherine Wheel"
    INDEX 01 53:09:45
  TRACK 16 AUDIO
    TITLE "Your Woman"
    PERFORMER "White Town"
    INDEX 00 57:07:10
    INDEX 01 57:07:32
  TRACK 17 AUDIO
    TITLE "Desire"
    PERFORMER "B.B.E."
    INDEX 01 61:26:02
  TRACK 18 AUDIO
    TITLE "I Will Fix You"
    PERFORMER "Kenickie"
    INDEX 00 65:18:70
    INDEX 01 65:19:22
  TRACK 19 AUDIO
    TITLE "Everest"
    PERFORMER "Supernaturals"
    INDEX 00 68:44:72
    INDEX 01 68:45:22
  TRACK 20 AUDIO
    TITLE "Tequila"
    PERFORMER "Terrorvision"
    ISRC GBAYE9802165
    INDEX 00 73:16:00
    INDEX 01 73:16:42`

**Comment by SokoloffA** [comment] 2021-02-24 20:42
For some reason, the program could not load the audio (the audio line is empty). The reasons may be follows:

1. *The flac program is not installed.*
    Make sure that the flac program is installed (main menu - preferences - programs).

2. *The program could not find the audio file for the CUE file. I see that the audio file has a suitable name (the name is similar to the name of the CUE file). But perhaps the audio file located in a different directory.*
Try selecting an audio file manually by clicking on the three dots next to the name of the audio file.

3. *The file is corrupted.*
Check the the audio file by running in the console 
```
flac -d "A Time To Remember - 1990 - Happy Birthday.flac"
```

![108365298-0c130080-71c5-11eb-9530-370e2a4b7a0a](https://user-images.githubusercontent.com/854935/109062923-98f41780-76f9-11eb-9a39-b10a2a1651c1.png)

**Comment by SokoloffA** [comment] 2021-02-24 20:47
I plan to improve reporting about problems. Now the program is too silent, it confuses people.

**Comment by SokoloffA** [comment] 2021-06-12 13:18
Reporting about problems was improved in the 7.0.0 release.


Added informative error messages when the program can’t load an audio file:
* The audio file does not exist.
* The audio file may be corrupted or an unsupported audio format.
* Decoder program is not installed.
* Decoder program is installed in the settings but binary file does not exist.

So I close the issue

**Comment by SokoloffA** [comment] 2021-10-31 09:33
@mpalourdio 
A very strange bug, I can't imagine how it is related to the "Destination directory". I'm intrigued, I really want to fix it.

Let's describe the process step by step. If I'm wrong, then correct me, any detail can make a difference here.

You are using Linux Mint 20.2 and Flacon 7.0.1.

1. The FLAC file and the CUE file are in a subdirectory in ~/Desktop.
2. You run the program 
3. You click the "Add disk" button
4. In the dialog that opens, you go to the directory on the desktop and double-click on the CUE file.
5. The program shows tracks, but don't load FLAC. I.e. the "Audio" field in the disc header is empty
6. If you click on the three dots near the "Audio" field, and select a FLAC file in the dialog, the program will successfully load it.

An alternative 
1. The same files are in a subdirectory in ~/Music, the directory name, count and names of files are similar to the previous case.
2. You run the program 
3. You click the "Add disk" button
4. In the dialog that opens, you go to the directory in ~/Music and double-click on the CUE file.
5. The program successfully loads both CUE and FLAC files

Please answer a couple of questions and run a some tests:
1. The full path to the desktop folder. Does the path contain spaces and non-Latin characters?
2. The search depends on the count and names of files in the directory with CUE. Please send me the full listing of the directory `ls -la` 

1. Put the files not on the desktop and not in ~/Music, but in a separate directory, say ~/flacon-issue-116. Will the program find the FLAC file?
2. Put the files not on the desktop and not in ~/Music, but in a directory with spaces in the name, say ~/"flacon issue 116". Will the program find the FLAC file?

Today I will install Mint in virtual machine (which edition do you use?) and I'll try to reproduce the bug.

**Comment by mpalourdio** [comment] 2021-10-31 10:33
Thanks for giving this a look! I'm on travel at the moment, I will provide you all the answers at the end of the afternoon (utc+1 here FWIW)

**Comment by mpalourdio** [comment] 2021-10-31 14:36
> You are using Linux Mint 20.2 and Flacon 7.0.1.
> 
>     1. The FLAC file and the CUE file are in a subdirectory in ~/Desktop.
> 
>     2. You run the program
> 
>     3. You click the "Add disk" button
> 
>     4. In the dialog that opens, you go to the directory on the desktop and double-click on the CUE file.
> 
>     5. The program shows tracks, but don't load FLAC. I.e. the "Audio" field in the disc header is empty
> 
>     6. If you click on the three dots near the "Audio" field, and select a FLAC file in the dialog, the program will successfully load it.
> 
> 
> An alternative
> 
>     1. The same files are in a subdirectory in ~/Music, the directory name, count and names of files are similar to the previous case.
> 
>     2. You run the program
> 
>     3. You click the "Add disk" button
> 
>     4. In the dialog that opens, you go to the directory in ~/Music and double-click on the CUE file.
> 
>     5. The program successfully loads both CUE and FLAC files
> 
> 

All of this is perfectly correct, and is what I'm experiencing! You've nailed it 100%

> Please answer a couple of questions and run a some tests:
> 
>     1. The full path to the desktop folder. Does the path contain spaces and non-Latin characters?

Full desktop path : /home/ben/Bureau/dylan/CD2 (Bureau is 'Desktop' in french)

>     2. The search depends on the count and names of files in the directory with CUE. Please send me the full listing of the directory `ls -la`

```shell
$ ls -la
total 78016
drwxrwxr-x 2 ben ben     4096 oct.  29 16:19  .
drwxrwxr-x 5 ben ben     4096 oct.  29 16:19  ..
-rw-rw-r-- 1 ben ben      381 oct.  29 16:19 'Bob Dylan - Rough and Rowdy Ways CD2.accurip'
-rw-rw-r-- 1 ben ben      304 oct.  29 16:19 'Bob Dylan - Rough and Rowdy Ways CD2.cue'
-rw-rw-r-- 1 ben ben 79806811 oct.  29 16:20 'Bob Dylan - Rough and Rowdy Ways CD2.flac'
-rw-rw-r-- 1 ben ben     3692 oct.  29 16:19 'Bob Dylan - Rough and Rowdy Ways CD2.log'
-rw-rw-r-- 1 ben ben     1046 oct.  29 16:19  foo_dr.txt
-rw-rw-r-- 1 ben ben      166 oct.  29 16:19 'Rough and Rowdy Ways CD2.txt'
```

> 
>     3. Put the files not on the desktop and not in ~/Music, but in a separate directory, say ~/flacon-issue-116. Will the program find the FLAC file?

```shell
$ pwd
/home/ben/flacon-issue-116/dylan/CD2
```
Flacon cannot find the flac here :(

>     4. Put the files not on the desktop and not in ~/Music, but in a directory with spaces in the name, say ~/"flacon issue 116". Will the program find the FLAC file?

```shell
$ pwd
/home/ben/flacon issue 116/dylan/CD2
```

Flacon cannot find the flac here :(

> 
> Today I will install Mint in virtual machine (which edition do you use?) and I'll try to reproduce the bug.

Hope this helps!

**Comment by SokoloffA** [comment] 2021-11-02 21:18
I couldn't reproduce the error. I added the printing of detailed logs. I have compiled a binary, I hope it will work on your distro. You don't need to install it, just run it from the console with the --debug parameter and send me the log.
```
./flacon --debug 2>&1 | tee flacon.log
```

[flacon.zip](https://github.com/flacon/flacon/files/7464060/flacon.zip)

**Comment by mpalourdio** [comment] 2021-11-03 09:46
Hello,

Thanks a lot. Very strange, because this compiled version really works great ! No bug at all. Maybe it has something to do with my installed version, as it's installed as Flatpak.

What do you think ?

**Comment by SokoloffA** [comment] 2021-11-03 16:25
Maybe this related with Flatpak. Tomorrow I will test the FlatPak version.

**Comment by SokoloffA** [comment] 2021-11-04 21:26
This is definitely related to Flatpack. flatpaked programs runs in the [sandbox with restrictions](https://docs.flatpak.org/en/latest/sandbox-permissions.html). 

Me and the Flatpak maintainer will release an update within a few days. While you can put the source files in ~/Music or ~/Downloads (access to these directories is allowed)

**Comment by mpalourdio** [comment] 2021-11-05 07:21
Meh, first time in my life that I install something with Flatpak :1st_place_medal: 

I have read the restrictions about filesystem permissions, and like everything is based onto $XDG, I can now understand why this fail. I think this sandboxing is a way too restricted IMHO. I can't see how allowing acess of `~/Downloads` (with a potential altered umask) is enforcing security. But, anyway, let's live with that non-sense.

Thanks a lot for investigating this weird issue. Patiently waiting for a next release anytime, now that this is spotted.

**Closed** 2021-11-27 10:43 UTC
Labels: done, Promised, Flatpak
